on: push
jobs:
  render-pdf:
    runs-on: ubuntu-latest
    steps:
    - name: HTML to PDF
      uses: fifsky/html-to-pdf-action@v0.1.0
      with:
        htmlFile: "./index.html"
        outputFile: "./resume.pdf"
  
